#!/usr/bin/env node

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = join(__dirname, '..')

const TOKENS_FILE = join(rootDir, 'src/gen/tokens.json')
const CONSTANTS_FILE = join(rootDir, 'src/gen/tokenConstants.ts')

function generatePaths(obj, prefix = '') {
  const paths = {}

  for (const [key, value] of Object.entries(obj)) {
    const currentPath = prefix ? `${prefix}.${key}` : key

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      if (
        Object.values(value).some(
          (v) => typeof v === 'string' || typeof v === 'number',
        )
      ) {
        paths[key] = currentPath
      }
      Object.assign(paths, { [key]: generatePaths(value, currentPath) })
    } else {
      paths[key] = currentPath
    }
  }

  return paths
}

function generateTokenConstants(tokens) {
  const sections = Object.keys(tokens).filter((key) => key !== 'breakpoints')
  const tokenPaths = {}

  sections.forEach((section) => {
    tokenPaths[section] = generatePaths(tokens[section], section)
  })

  const tokensObject = sections
    .map(
      (section) =>
        `  ${section}: ${JSON.stringify(tokenPaths[section], null, 4)}`,
    )
    .join(',\n')

  const typeUnions = sections
    .map((section) => `  | \`${section}.\${string}\``)
    .join('\n')

  return `// Auto-generated design token constants
// Generated by: scripts/designTokens.js
// Do not edit this file manually

export const TOKENS = {
${tokensObject},
  breakpoints: {
    mobile: 'breakpoints.mobile',
    tablet: 'breakpoints.tablet',
    desktop: 'breakpoints.desktop',
    wide: 'breakpoints.wide'
  }
} as const

export type TokenPath = 
${typeUnions}
  | \`breakpoints.\${string}\`
`
}

function loadTokensFromFile() {
  const fileContent = readFileSync(TOKENS_FILE, 'utf8')
  return JSON.parse(fileContent)
}

function saveTokensToFile(tokens) {
  const dir = dirname(TOKENS_FILE)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
  writeFileSync(TOKENS_FILE, JSON.stringify(tokens, null, 2))
}

function generateConstants() {
  console.log('Generating TypeScript constants from tokens.json...')

  const tokens = loadTokensFromFile()
  const constantsContent = generateTokenConstants(tokens)

  const dir = dirname(CONSTANTS_FILE)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }

  writeFileSync(CONSTANTS_FILE, constantsContent)
  console.log(`✅ Generated token constants: ${CONSTANTS_FILE}`)
}

async function uploadToFirebase() {
  console.log('Uploading tokens to Firebase Remote Config...')

  try {
    const { initializeApp } = await import('firebase/app')
    const { getRemoteConfig, setParameter, publishTemplate } = await import(
      'firebase/remote-config'
    )

    const serviceAccountPath = process.env.FIREBASE_SERVICE_ACCOUNT_PATH
    if (!serviceAccountPath) {
      throw new Error(
        'FIREBASE_SERVICE_ACCOUNT_PATH environment variable is required for uploads',
      )
    }

    if (!existsSync(serviceAccountPath)) {
      throw new Error(`Service account file not found: ${serviceAccountPath}`)
    }

    const serviceAccount = JSON.parse(readFileSync(serviceAccountPath, 'utf8'))

    const app = initializeApp({
      credential: serviceAccount,
      projectId: serviceAccount.project_id,
    })

    const remoteConfig = getRemoteConfig(app)
    const tokens = loadTokensFromFile()

    await setParameter(remoteConfig, 'design_tokens', {
      defaultValue: { value: JSON.stringify(tokens) },
      description: 'Design tokens for the application',
    })

    await publishTemplate(remoteConfig)
    console.log('✅ Tokens uploaded to Firebase Remote Config')
  } catch (error) {
    console.error('❌ Failed to upload to Firebase:', error.message)
    process.exit(1)
  }
}

async function downloadFromFirebase() {
  console.log('Downloading tokens from Firebase Remote Config...')

  try {
    const { designTokensClient } = await import('../src/lib/designTokens.js')

    designTokensClient.clearCache()
    const tokens = await designTokensClient.getAllTokens()

    saveTokensToFile(tokens)
    console.log(`✅ Downloaded tokens to: ${TOKENS_FILE}`)

    generateConstants()
  } catch (error) {
    console.error('❌ Failed to download from Firebase:', error.message)
    process.exit(1)
  }
}

function showHelp() {
  console.log(`
Design Tokens Management Script

Usage:
  pnpm tokens generate    - Generate TypeScript constants from tokens.json
  pnpm tokens upload      - Upload tokens.json to Firebase Remote Config
  pnpm tokens download    - Download tokens from Firebase to tokens.json
  pnpm tokens sync        - Download + generate (full sync)

Environment Variables:
  FIREBASE_SERVICE_ACCOUNT_PATH - Path to Firebase service account JSON (required for upload)

Files:
  ${TOKENS_FILE} - Local design tokens JSON file
  ${CONSTANTS_FILE} - Generated TypeScript constants
`)
}

async function main() {
  const command = process.argv[2]

  switch (command) {
    case 'generate':
      generateConstants()
      break
    case 'upload':
      await uploadToFirebase()
      break
    case 'download':
      await downloadFromFirebase()
      break
    case 'sync':
      await downloadFromFirebase()
      break
    case 'help':
    case '--help':
    case '-h':
      showHelp()
      break
    default:
      console.error('Invalid command. Use "help" to see available commands.')
      process.exit(1)
  }
}

main().catch((error) => {
  console.error('Script failed:', error)
  process.exit(1)
})
